# data
data:
  eval_data: ''
  shuffle: true
  train_data: '/root/moshi-data-prep/finetune_data/dataset.jsonl'

# model
moshi_paths:
  hf_repo_id: "kyutai/moshiko-pytorch-bf16"

full_finetuning: false
lora:
  enable: true
  rank: 128
  scaling: 2.0
  ft_embed: true   # ← très important pour le français

first_codebook_weight_multiplier: 100.0
text_padding_weight: 0.5

# optim
duration_sec: 128.0
batch_size: 24          # ← changé pour éviter le bug
max_steps: 2000
gradient_checkpointing: true
num_microbatches: 1

optim:
  lr: 3e-5
  weight_decay: 0.1
  pct_start: 0.05

# other
seed: 0
log_freq: 1
eval_freq: 100
do_eval: false
do_ckpt: true
ckpt_freq: 200
num_ckpt_keep: 3
save_adapters: true
run_dir: "/root/moshi-finetune/runs/french_moshi"   # ← nom plus clair
overwrite_run_dir: true

# tracking (tu peux garder)
aim:
  experiment: "moshi-french-finetune"
  repo: "/root/moshi-finetune/aim_data"
  run_name: "french_moshi"